### ISSUE TITLE
使用yapi的1.5.10版本，安装完成后并没有出现RAP项目导入的菜单

### ISSUE THREAD

**Issue by jelver** [wxxcarl/yapi-plugin-import-rap#1]
已确认安装插件过程没有问题，但并未出现文档里面描述的 ” 在yapi项目的菜单中会增加“Rap项目导入菜单 “ 入口？ 是否忽略了什么设置，谢谢

**Comment by wxxcarl** [comment]
config.json 配置了吗

**Comment by jelver** [comment]
> config.json 配置了吗

配置了的,

   "plugins": [{
    "name": "import-rap",
    "options": {
        "rapOrigin": "http://rap.xxx.com"   //xxx是我们的业务域名
    }
  }]

**Comment by wxxcarl** [comment]
`yapi plugin --name yapi-plugin-import-rap`

**Comment by wxxcarl** [comment]
安装完了记得重启一下

**Comment by jelver** [comment]
> 安装完了记得重启一下

好的，那我试试，另外如果可以的话建议你update一下到安装说明日志，否则其他人可能也会碰到这个问题，谢谢

**Comment by jelver** [comment]
> `yapi plugin --name yapi-plugin-import-rap`

问个低级问题，这个命令是在哪里执行呢， 在docker里面是无法识别这个指令

**Comment by wxxcarl** [comment]
应该是在你配置的那个目录，config.json,看下文档

**Comment by jelver** [comment]
yapi 需要装 其cli 包可以解决了，
npm install -g yapi-cli --registry https://registry.npm.taobao.org

但是执行插件安装语句 yapi plugin --name yapi-plugin-import-rap
出现了大量的报错日志，我截取部分：
`[error] ./client/containers/Project/Interface/InterfaceCol/InterfaceColContent.js

/api/vendors/client/containers/Project/Interface/InterfaceCol/InterfaceColContent.js
    2:10  error  'connect' is defined but never used                                                                                                                                                                                                                                                                            no-unused-vars
    4:10  error  'withRouter' is defined but never used                                                                                                                                                                                                                                                                         no-unused-vars
    9:3   error  'fetchInterfaceColList' is defined but never used                                                                                                                                                                                                                                                              no-unused-vars
   10:3   error  'fetchCaseList' is defined but never used                                                                                                                                                                                                                                                                      no-unused-vars
   11:3   error  'setColData' is defined but never used                                                                                                                                                                                                                                                                         no-unused-vars
   12:3   error  'fetchCaseEnvList' is defined but never used                                                                                                                                                                                                                                                                   no-unused-vars
   14:8   error  'HTML5Backend' is defined but never used                                                                                                                                                                                                                                                                       no-unused-vars
   15:10  error  'getToken' is defined but never used                                                                                                                                                                                                                                                                           no-unused-vars
   15:20  error  'getEnv' is defined but never used                                                                                                                                                                                                                                                                             no-unused-vars
   16:10  error  'DragDropContext' is defined but never used                                                                                                                                                                                                                                                                    no-unused-vars
   82:10  error  'propTypes' is not defined                                                                                                                                                                                                                                                                                     no-undef
  167:9   error  componentWillMount is deprecated since React 16.999.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components                       react/no-deprecated
  189:3   error  'handleChangeInterfaceCol' is not defined                                                                                                                                                                                                                                                                      no-undef
  207:3   error  'handleReqHeader' is not defined                                                                                                                                                                                                                                                                               no-undef
  227:3   error  'handleColdata' is not defined                                                                                                                                                                                                                                                                                 no-undef
  243:3   error  'executeTests' is not defined                                                                                                                                                                                                                                                                                  no-undef
  301:3   error  'handleTest' is not defined                                                                                                                                                                                                                                                                                    no-undef
  379:3   error  'handleScriptTest' is not defined                                                                                                                                                                                                                                                                              no-undef
  402:3   error  'handleValue' is not defined                                                                                                                                                                                                                                                                                   no-undef
  408:3   error  'arrToObj' is not defined                                                                                                                                                                                                                                                                                      no-undef
  426:3   error  'onDrop' is not defined                                                                                                                                                                                                                                                                                        no-undef
  443:3   error  'onChangeTest' is not defined                                                                                                                                                                                                                                                                                  no-undef
  456:3   error  'handleInsertCode' is not defined                                                                                                                                                                                                                                                                              no-undef
  460:9   error  componentWillReceiveProps is deprecated since React 16.999.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
  470:3   error  'changeCollapseClose' is not defined                                                                                                                                                                                                                                                                           no-undef
  483:3   error  'openReport' is not defined                                                                                                                                                                                                                                                                                    no-undef
  490:3   error  'openAdv' is not defined                                                                                                                                                                                                                                                                                       no-undef
  501:3   error  'handleScriptChange' is not defined                                                                                                                                                                                                                                                                            no-undef
  505:3   error  'handleAdvCancel' is not defined                                                                                                                                                                                                                                                                               no-undef
  509:3   error  'handleAdvOk' is not defined                                                                                                                                                                                                                                                                                   no-undef
  531:3   error  'handleCancel' is not defined                                                                                                                                                                                                                                                                                  no-undef
  535:3   error  'currProjectEnvChange' is not defined                                                                                                                                                                                                                                                                          no-undef
  545:3   error  'autoTests' is not defined                                                                                                                                                                                                                                                                                     no-undef
  549:3   error  'handleAuto' is not defined                                                                                                                                                                                                                                                                                    no-undef
  560:3   error  'copyUrl' is not defined                                                                                                                                                                                                                                                                                       no-undef
  565:3   error  'modeChange' is not defined                                                                                                                                                                                                                                                                                    no-undef
  569:3   error  'emailChange' is not defined                                                                                                                                                                                                                                                                                   no-undef
  573:3   error  'downloadChange' is not defined                                                                                                                                                                                                                                                                                no-undef
  577:3   error  'handleColEnvObj' is not defined                                                                                                                                                                                                                                                                               no-undef
  585:3   error  'handleCommonSetting' is not defined                                                                                                                                                                                                                                                                           no-undef
  607:3   error  'cancelCommonSetting' is not defined                                                                                                                                                                                                                                                                           no-undef
  613:3   error  'openCommonSetting' is not defined                                                                                                                                                                                                                                                                             no-undef
  619:3   error  'changeCommonFieldSetting' is not defined                                                                                                                                                                                                                                                                      no-undef

✖ 43 problems (43 errors, 0 warnings)


[error] ./client/containers/Project/Interface/InterfaceList/Edit.js

/api/vendors/client/containers/Project/Interface/InterfaceList/Edit.js
    3:10  error  'connect' is defined but never used                 no-unused-vars
    6:3   error  'updateInterfaceData' is defined but never used     no-unused-vars
    7:3   error  'fetchInterfaceListMenu' is defined but never used  no-unused-vars
    8:3   error  'fetchInterfaceData' is defined but never used      no-unused-vars
   10:10  error  'getProject' is defined but never used              no-unused-vars
   32:10  error  'propTypes' is not defined                          no-undef
   60:3   error  'onSubmit' is not defined                           no-undef
  144:3   error  'onTagClick' is not defined                         no-undef
  150:3   error  'handleOk' is not defined                           no-undef
  175:3   error  'handleCancel' is not defined                       no-undef
  181:3   error  'tagSubmit' is not defined                          no-undef

✖ 11 problems (11 errors, 0 warnings)


[error] ./client/containers/Project/Interface/InterfaceList/AddInterfaceForm.js

/api/vendors/client/containers/Project/Interface/InterfaceList/AddInterfaceForm.js
  18:10  error  'propTypes' is not defined     no-undef
  25:3   error  'handleSubmit' is not defined  no-undef
  37:3   error  'handlePath' is not defined    no-undef

✖ 3 problems (3 errors, 0 warnings)


[error] ./client/containers/Project/Interface/InterfaceList/Run/Run.js

/api/vendors/client/containers/Project/Interface/InterfaceList/Run/Run.js
   3:10  error  'connect' is defined but never used                                                                                                                                                                                                                                                                            no-unused-vars
   4:10  error  'withRouter' is defined but never used                                                                                                                                                                                                                                                                         no-unused-vars
  21:10  error  'propTypes' is not defined                                                                                                                                                                                                                                                                                     no-undef
  27:3   error  'state' is not defined                                                                                                                                                                                                                                                                                         no-undef
  33:3   error  componentWillMount is deprecated since React 16.999.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components                       react/no-deprecated
  35:3   error  componentWillReceiveProps is deprecated since React 16.999.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
  37:3   error  'savePostmanRef' is not defined                                                                                                                                                                                                                                                                                no-undef
  41:3   error  'saveCase' is not defined                                                                                                                                                                                                                                                                                      no-undef

✖ 8 problems (8 errors, 0 warnings)


[error] ./client/containers/Project/Setting/ProjectEnv/ProjectEnvContent.js

/api/vendors/client/containers/Project/Setting/ProjectEnv/ProjectEnvContent.js
   31:10  error  'propTypes' is not defined                                                                                                                                                                                                                                                                                     no-undef
   95:3   error  'addHeader' is not defined                                                                                                                                                                                                                                                                                     no-undef
  106:3   error  'delHeader' is not defined                                                                                                                                                                                                                                                                                     no-undef
  122:3   error  componentWillReceiveProps is deprecated since React 16.999.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
  130:3   error  'handleOk' is not defined                                                                                                                                                                                                                                                                                      no-undef

✖ 5 problems (5 errors, 0 warnings)


[error] ./client/components/EasyDragSort/EasyDragSort.js

/api/vendors/client/components/EasyDragSort/EasyDragSort.js
  26:10  error  'propTypes' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)


[error] ./client/components/AceEditor/AceEditor.js

/api/vendors/client/components/AceEditor/AceEditor.js
  25:10  error  'propTypes' is not defined                                                                                                                                                                                                                                                                                     no-undef
  52:3   error  componentWillReceiveProps is deprecated since React 16.999.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

✖ 2 problems (2 errors, 0 warnings)


[error] ./client/containers/Project/Interface/InterfaceList/AddInterfaceCatForm.js

/api/vendors/client/containers/Project/Interface/InterfaceList/AddInterfaceCatForm.js
   9:10  error  'propTypes' is not defined     no-undef
  15:3   error  'handleSubmit' is not defined  no-undef

✖ 2 problems (2 errors, 0 warnings)


[error] ./client/components/Label/Label.js

/api/vendors/client/components/Label/Label.js
  14:10  error  'propTypes' is not defined                                                                                                                                                                                                                                                                                     no-undef
  19:3   error  'toggle' is not defined                                                                                                                                                                                                                                                                                        no-undef
  22:3   error  'handleChange' is not defined                                                                                                                                                                                                                                                                                  no-undef
  25:3   error  componentWillReceiveProps is deprecated since React 16.999.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated

✖ 4 problems (4 errors, 0 warnings)


[error] ./client/containers/Project/Interface/InterfaceList/View.js

/api/vendors/client/containers/Project/Interface/InterfaceList/View.js
    3:10  error  'connect' is defined but never used  no-unused-vars
   32:10  error  'propTypes' is not defined           no-undef
  227:3   error  'enterItem' is not defined           no-undef
  233:3   error  'leaveItem' is not defined           no-undef
  239:3   error  'copyUrl' is not defined             no-undef
  244:3   error  'flagMsg' is not defined             no-undef

✖ 6 problems (6 errors, 0 warnings)


[error] ./client/containers/Project/Interface/InterfaceCol/ImportInterface.js

/api/vendors/client/containers/Project/Interface/InterfaceCol/ImportInterface.js
   5:10  error  'connect' is defined but never used                 no-unused-vars
   7:10  error  'fetchInterfaceListMenu' is defined but never used  no-unused-vars
  25:3   error  'state' is not defined                              no-undef
  31:10  error  'propTypes' is not defined                          no-undef
  45:3   error  'onChange' is not defined                           no-undef

✖ 5 problems (5 errors, 0 warnings)


[error] ./client/containers/Project/Setting/ProjectMessage/ProjectTag.js

/api/vendors/client/containers/Project/Setting/ProjectMessage/ProjectTag.js
   8:10  error  'propTypes' is not defined     no-undef
  43:3   error  'addHeader' is not defined     no-undef
  55:3   error  'delHeader' is not defined     no-undef
  64:3   error  'handleChange' is not defined  no-undef

✖ 4 problems (4 errors, 0 warnings)


[error] ./client/components/ModalPostman/index.js

/api/vendors/client/components/ModalPostman/index.js
   37:10  error  'propTypes' is not defined                                                                                                                                                                                                                                                                no-undef
   64:3   error  componentWillMount is deprecated since React 16.999.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
  135:3   error  'handleConstantsInput' is not defined                                                                                                                                                                                                                                                     no-undef
  143:3   error  'handleParamsInput' is not defined                                                                                                                                                                                                                                                        no-undef
  152:3   error  'MethodsListSource' is not defined                                                                                                                                                                                                                                                        no-undef
  193:3   error  'handleCancel' is not defined                                                                                                                                                                                                                                                             no-undef
  199:3   error  'handleOk' is not defined                                                                                                                                                                                                                                                                 no-undef
  204:3   error  'handleCollapse' is not defined                                                                                                                                                                                                                                                           no-undef

✖ 8 problems (8 errors, 0 warnings)


[error] ./client/components/CaseEnv/index.js

/api/vendors/client/components/CaseEnv/index.js
  15:10  error  'propTypes' is not defined  no-undef
  23:3   error  'callback' is not defined   no-undef

✖ 2 problems (2 errors, 0 warnings)


[error] ./client/containers/Project/Interface/InterfaceList/Run/AddColModal.js

/api/vendors/client/containers/Project/Interface/InterfaceList/Run/AddColModal.js
   2:10  error  'connect' is defined but never used                                                                                                                                                                                                                                                                            no-unused-vars
   6:10  error  'withRouter' is defined but never used                                                                                                                                                                                                                                                                         no-unused-vars
   7:10  error  'fetchInterfaceColList' is defined but never used                                                                                                                                                                                                                                                              no-unused-vars
  22:10  error  'propTypes' is not defined                                                                                                                                                                                                                                                                                     no-undef
  32:3   error  'state' is not defined                                                                                                                                                                                                                                                                                         no-undef
  44:3   error  componentWillMount is deprecated since React 16.999.0, use UNSAFE_componentWillMount instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillmount. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components                       react/no-deprecated
  49:3   error  componentWillReceiveProps is deprecated since React 16.999.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
  54:3   error  'addCol' is not defined                                                                                                                                                                                                                                                                                        no-undef
  68:3   error  'select' is not defined                                                                                                                                                                                                                                                                                        no-undef

✖ 9 problems (9 errors, 0 warnings)


[error] ./client/components/SchemaTable/SchemaTable.js

/api/vendors/client/components/SchemaTable/SchemaTable.js
  105:10  error  'propTypes' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)


[error] ./client/components/ModalPostman/MockList.js

/api/vendors/client/components/ModalPostman/MockList.js
   9:10  error  'propTypes' is not defined  no-undef
  28:3   error  'onFilter' is not defined   no-undef

✖ 2 problems (2 errors, 0 warnings)


[error] ./client/components/ModalPostman/MethodsList.js

/api/vendors/client/components/ModalPostman/MethodsList.js
  27:10  error  'propTypes' is not defined             no-undef
  44:3   error  'showMore' is not defined              no-undef
  59:3   error  'inputComponent' is not defined        no-undef
  73:3   error  'doubleInputComponent' is not defined  no-undef
  96:3   error  'selectComponent' is not defined       no-undef

✖ 5 problems (5 errors, 0 warnings)


[error] ./client/components/ModalPostman/VariablesSelect.js

/api/vendors/client/components/ModalPostman/VariablesSelect.js
   4:10  error  'connect' is defined but never used                                                                                                                                                                                                                                                                            no-unused-vars
   5:10  error  'fetchVariableParamsList' is defined but never used                                                                                                                                                                                                                                                            no-unused-vars
  32:10  error  'propTypes' is not defined                                                                                                                                                                                                                                                                                     no-undef
  39:3   error  'state' is not defined                                                                                                                                                                                                                                                                                         no-undef
  79:9   error  componentWillReceiveProps is deprecated since React 16.999.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops. Use https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles to automatically update your components  react/no-deprecated
  85:3   error  'handleSelect' is not defined                                                                                                                                                                                                                                                                                  no-undef
  99:3   error  'onExpand' is not defined                                                                                                                                                                                                                                                                                      no-undef

✖ 7 problems (7 errors, 0 warnings)


[error] ./client/containers/Project/Interface/InterfaceList/InterfaceEditForm.js

/api/vendors/client/containers/Project/Interface/InterfaceList/InterfaceEditForm.js
    3:10  error  'connect' is defined but never used           no-unused-vars
    7:10  error  'changeEditStatus' is defined but never used  no-unused-vars
  120:10  error  'propTypes' is not defined                    no-undef
  222:3   error  'handleSubmit' is not defined                 no-undef
  357:3   error  'onChangeMethod' is not defined               no-undef
  400:3   error  'addParams' is not defined                    no-undef
  407:3   error  'delParams' is not defined                    no-undef
  417:3   error  'handleMockPreview' is not defined            no-undef
  439:3   error  'handleJsonType' is not defined               no-undef
  489:3   error  'changeRadioGroup' is not defined             no-undef
  499:3   error  '_changeRadioGroup' is not defined            no-undef
  515:3   error  'handleDragMove' is not defined               no-undef
  526:3   error  'handleResBody' is not defined                no-undef
  535:3   error  'handleReqBody' is not defined                no-undef
  544:3   error  'handleBulkOk' is not defined                 no-undef
  565:3   error  'handleBulkCancel' is not defined             no-undef
  573:3   error  'showBulk' is not defined                     no-undef
  588:3   error  'handleBulkValueInput' is not defined         no-undef

✖ 18 problems (18 errors, 0 warnings)


编译客户端成功，请重启服务器
`

**Comment by wxxcarl** [comment]
这些都是yapi的报错，都是eslint校验没通过，跟插件本身没有关系

**Comment by xuzhou-99** [comment]
这些都是yapi的报错，都是eslint校验没通过，跟插件本身没有关系
重启服务之后，页面展示不了，报错Uncaught Error: Cannot find module "./../../../../../nodejs/node_global/node_modules/ykit/node_modules/webpack/buildin/module.js"，这个可能是什么原因呢，eslint校验没通过会有影响嘛，有的话怎么处理呢
